import type { Config } from "tailwindcss";

/**
 * BEE Standards & Labelling Portal — design system.
 * Tokens ported verbatim from the approved reference landing page so every
 * screen (public portal + the 140 internal screens) shares one visual language.
 */
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // BEE blue palette (matched to beeindia.gov.in)
        "surface-tint": "#1f4f9c",
        "on-primary-fixed": "#001b4d",
        "inverse-primary": "#9dbdec",
        "on-tertiary-fixed": "#001d33",
        "surface-card": "#FFFFFF",
        "on-secondary": "#ffffff",
        "primary-container": "#254e9e",
        "solar-gold-light": "#FEF3C7",
        "on-surface": "#181c20",
        "border-subtle": "#E2E8F0",
        "tertiary-container": "#0e5f96",
        "on-secondary-fixed": "#001b3c",
        "surface-container-highest": "#e0e3e8",
        "secondary-fixed": "#d6e3ff",
        "surface-dim": "#d7dadf",
        "on-secondary-container": "#3f5882",
        secondary: "#2e3192",
        "tertiary-fixed": "#8fd6f7",
        "surface-ground": "#F6F9FE",
        background: "#f5f8ff",
        "on-tertiary-container": "#6cc6ef",
        "navy-subtle": "#EDF2F7",
        "surface-container-low": "#eef3fb",
        "inverse-surface": "#2d3135",
        tertiary: "#0b4a7a",
        "error-container": "#ffdad6",
        outline: "#6b7280",
        "on-surface-variant": "#3f4650",
        "solar-gold-dark": "#B45309",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#9dbdec",
        "forest-light": "#E7EFFB",
        "secondary-fixed-dim": "#adc7f7",
        error: "#ba1a1a",
        "navy-dark": "#0F172A",
        "forest-dark": "#14315E",
        "tertiary-fixed-dim": "#4ec4ef",
        "on-primary": "#ffffff",
        "primary-fixed": "#c9d9f7",
        "on-error": "#ffffff",
        "outline-variant": "#c4cbd6",
        "inverse-on-surface": "#eef1f6",
        "on-primary-fixed-variant": "#18408f",
        "star-active": "#FFB800",
        "on-primary-container": "#b6cdf0",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004a72",
        "solar-gold": "#F59E0B",
        "surface-container-high": "#e5e8ee",
        surface: "#f5f8ff",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9ff",
        "on-background": "#181c20",
        "surface-container": "#e9eef7",
        "on-secondary-fixed-variant": "#2d476f",
        "secondary-container": "#b6d0ff",
        "border-strong": "#CBD5E1",
        "surface-variant": "#e0e3e8",
        primary: "#1f3c88",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        // refined, blue-tinted elevation for a premium-but-official feel
        card: "0 1px 2px rgba(16,42,94,0.05), 0 8px 20px -6px rgba(16,42,94,0.10)",
        elevated: "0 16px 40px -12px rgba(16,42,94,0.20)",
        header: "0 2px 12px rgba(16,42,94,0.08)",
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-2xl": "4rem",
        margin: "2rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "margin-desktop": "3rem",
        gutter: "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "title-lg": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "system-ui", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "headline-xl-mobile": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "title-lg": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
